# ArchEHR-QA: BioBERT two-stage RAG + Qwen2.5-3B

Upload the companion `archehr_sml_rag.py` and the extracted ArchEHR-QA dataset as Kaggle datasets, enable Internet and select **GPU T4 x2**. Edit `CODE_ROOT` and `DATA_ROOT` in the next cell to match Kaggle's dataset slugs. The script preserves the paper's architecture while using a 4-bit small language model.

In [4]:
!pip -q install -U "transformers>=4.46" "accelerate>=0.34" bitsandbytes sentence-transformers datasets scikit-learn lxml rouge-score sacrebleu

import re
import json
import shutil
import pandas as pd
import seaborn as sns
from pathlib import Path
from google.colab import files
import matplotlib.pyplot as plt
from sacrebleu import corpus_bleu
from rouge_score import rouge_scorer

In [5]:
CODE_FILE = Path("/content/archehr_sml_rag.py")
assert CODE_FILE.exists(), "فایل archehr_sml_rag.py را Upload کن."

zip_files = list(Path("/content").glob("*.zip"))
assert zip_files, "فایل ZIP دیتاست را Upload کن."

ZIP_FILE = zip_files[0]
EXTRACT_DIR = Path("/content/archehr_data")
EXTRACT_DIR.mkdir(exist_ok=True)

shutil.unpack_archive(str(ZIP_FILE), str(EXTRACT_DIR))

dev_xml_files = list(EXTRACT_DIR.rglob("dev/archehr-qa.xml"))
assert dev_xml_files, "فایل dev/archehr-qa.xml پس از extract پیدا نشد."

DATA_ROOT = str(dev_xml_files[0].parent.parent)
print("Dataset path:", DATA_ROOT)

text = CODE_FILE.read_text()

text = "\n".join(
    line for line in text.splitlines()
    if not line.lstrip().startswith("!pip")
)

text = re.sub(
    r'DATA_ROOT = Path\([^)]+\)',
    f"DATA_ROOT = Path({DATA_ROOT!r})",
    text,
    count=1,
)

text = re.sub(
    r'OUT = Path\([^)]+\)',
    'OUT = Path("/content/archehr_sml_rag")',
    text,
    count=1,
)

RUN_FILE = Path("/content/run_archehr_sml_rag.py")
RUN_FILE.write_text(text)

%run /content/run_archehr_sml_rag.py

Dataset path: /content/archehr_data/archehr-qa-a-dataset-for-addressing-patients-information-needs-related-to-clinical-course-of-hospitalization-1.3
GPU(s): 1 | data: /content/archehr_data/archehr-qa-a-dataset-for-addressing-patients-information-needs-related-to-clinical-course-of-hospitalization-1.3
Loaded 20 labelled development and 100 test cases
{0: 239, 1: 95} validation cases: ['1' '5' '7' '10']

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/1.11k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

[transformers] You passed `num_labels=1` which is incompatible to the `id2label` map of length `2`.

pytorch_model.bin: reconstructing file:   0%|          |  0.00B /  436MB

pytorch_model.bin: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: dmis-lab/biobert-base-cased-v1.2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.decoder.bias               | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

model.safetensors: reconstructing file:   0%|          |  0.00B /  436MB

model.safetensors: downloading bytes:           |  0.00B

epoch=1: P=0.000, R=0.000, F1=0.000

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

epoch=2: P=0.000, R=0.000, F1=0.000
epoch=3: P=0.143, R=0.038, F1=0.061

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

epoch=4: P=0.222, R=0.231, F1=0.226

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

epoch=5: P=0.240, R=0.231, F1=0.235

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

epoch=6: P=0.259, R=0.269, F1=0.264

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

epoch=7: P=0.219, R=0.269, F1=0.241
epoch=8: P=0.222, R=0.308, F1=0.258
Early stop

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/4.32k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/610 [00:00<?, ?B/s]

pytorch_model.bin: reconstructing file:   0%|          |  0.00B /  433MB

pytorch_model.bin: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  433MB

model.safetensors: downloading bytes:           |  0.00B

tokenizer_config.json:   0%|          | 0.00/546 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/661 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json:   0%|          | 0.00/35.6k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

,case_id,answer,confidence_self_consistency
0,1,"Based on the evidence, ERCP was recommended af...",0.852971

,claim,supporting_sentence_ids,supporting_sentences
0,"Based on the evidence, ERCP was recommended af...","[8, 2]","[As the patient's INR was normalized to 1.2, a..."
1,"Due to the patient's elevated INR, a sphincter...","[8, 6]","[As the patient's INR was normalized to 1.2, a..."
2,The patient was put on IV Zosyn for at least a...,"[8, 2]","[As the patient's INR was normalized to 1.2, a..."
3,Medication alone may not have fully cleared th...,"[8, 5]","[As the patient's INR was normalized to 1.2, a..."

In [6]:
val_case_ids = set(val_df["case_id"])
validation_cases = [c for c in dev_cases if c.case_id in val_case_ids]

def cited_sentence_ids(answer):
    groups = re.findall(r"\[([^\]]+)\]", answer)
    return {
        item
        for group in groups
        for item in re.findall(r"\d+", group)
    }

def set_prf(predicted, gold):
    predicted, gold = set(predicted), set(gold)
    tp = len(predicted & gold)
    precision = tp / len(predicted) if predicted else 0.0
    recall = tp / len(gold) if gold else 0.0
    f1 = (
        2 * precision * recall / (precision + recall)
        if precision + recall else 0.0
    )
    return precision, recall, f1

validation_results = [answer_case(case) for case in validation_cases]

rows = []
rouge = rouge_scorer.RougeScorer(["rougeL"], use_stemmer=True)

for case, result in zip(validation_cases, validation_results):
    gold_evidence = {
        sentence_id
        for sentence_id, label in case.labels.items()
        if label == "essential"
    }

    retrieved_evidence = {item["id"] for item in result["evidence"]}
    cited_evidence = cited_sentence_ids(result["answer"])

    retrieval_p, retrieval_r, retrieval_f1 = set_prf(
        retrieved_evidence, gold_evidence
    )
    citation_p, citation_r, citation_f1 = set_prf(
        cited_evidence, gold_evidence
    )

    rouge_l = rouge.score(
        case.answer,
        result["answer"]
    )["rougeL"].fmeasure

    rows.append({
        "case_id": case.case_id,
        "retrieval_precision": retrieval_p,
        "retrieval_recall": retrieval_r,
        "retrieval_f1": retrieval_f1,
        "citation_precision": citation_p,
        "citation_recall": citation_r,
        "citation_f1": citation_f1,
        "rougeL": rouge_l,
        "self_consistency_confidence": result["confidence_self_consistency"],
        "reference_answer": case.answer,
        "generated_answer": result["answer"],
        "evidence_trace": result["evidence_trace"],
    })

evaluation_df = pd.DataFrame(rows)

bleu = corpus_bleu(
    evaluation_df["generated_answer"].tolist(),
    [evaluation_df["reference_answer"].tolist()]
).score

print("===== Mean validation metrics =====")
print(evaluation_df[
    [
        "retrieval_precision",
        "retrieval_recall",
        "retrieval_f1",
        "citation_precision",
        "citation_recall",
        "citation_f1",
        "rougeL",
        "self_consistency_confidence",
    ]
].mean())

print(f"\nBLEU: {bleu:.2f}")

display(evaluation_df)

evaluation_df.to_csv(
    "/content/archehr_sml_rag/validation_evaluation.csv",
    index=False,
)

===== Mean validation metrics =====
retrieval_precision            0.264957
retrieval_recall               0.529762
retrieval_f1                   0.350975
citation_precision             0.354167
citation_recall                0.321429
citation_f1                    0.330556
rougeL                         0.213259
self_consistency_confidence    0.772857
dtype: float64

BLEU: 9.53

,case_id,retrieval_precision,retrieval_recall,retrieval_f1,citation_precision,citation_recall,citation_f1,rougeL,self_consistency_confidence,reference_answer,generated_answer,evidence_trace
0,1,0.444444,1.000000,0.615385,0.500000,0.500000,0.500000,0.243590,0.852971,An endoscopic retrograde cholangiopancreatogra...,"Based on the evidence, ERCP was recommended af...","[{'claim': 'Based on the evidence, ERCP was re..."
1,5,0.153846,0.285714,0.200000,0.250000,0.285714,0.266667,0.212500,0.737147,"The chest pain was musculoskeletal, not overdo...",The patient experienced chest pain after overd...,[{'claim': 'The patient experienced chest pain...
2,7,0.230769,0.500000,0.315789,0.333333,0.166667,0.222222,0.225166,0.786964,The patient no longer needs to take her Coumad...,"After a subarachnoid hemorrhage, the patient r...","[{'claim': 'After a subarachnoid hemorrhage, t..."
3,10,0.230769,0.333333,0.272727,0.333333,0.333333,0.333333,0.171779,0.714347,The patient had a pulseless electrical activit...,"Based on the evidence, it seems your friend li...","[{'claim': 'Based on the evidence, it seems yo..."

In [ ]:
OUT = Path("/content/archehr_sml_rag")
OUT.mkdir(parents=True, exist_ok=True)

results = [answer_case(case) for case in test_cases]

output_df = pd.DataFrame([
    {
        "case_id": result["case_id"],
        "answer": result["answer"],
        "confidence_self_consistency": result["confidence_self_consistency"],
        "evidence_trace": json.dumps(result["evidence_trace"]),
    }
    for result in results
])

output_path = OUT / "test_predictions.csv"
output_df.to_csv(output_path, index=False)

full_path = OUT / "test_predictions_full.json"
full_path.write_text(json.dumps(results, indent=2))

print(f"Saved: {output_path}")

files.download("/content/archehr_sml_rag/test_predictions.csv")

In [ ]:
sns.set_theme(style="whitegrid")

plot_df = evaluation_df.copy()

plot_df["trace_claim_count"] = plot_df["evidence_trace"].apply(len)
plot_df["avg_evidence_per_claim"] = plot_df["evidence_trace"].apply(
    lambda trace: (
        sum(len(item["supporting_sentence_ids"]) for item in trace) / len(trace)
        if len(trace) else 0
    )
)

fig, axes = plt.subplots(2, 2, figsize=(18, 12))

mean_metrics = plot_df[
    [
        "retrieval_precision",
        "retrieval_recall",
        "retrieval_f1",
        "citation_precision",
        "citation_recall",
        "citation_f1",
        "rougeL",
        "self_consistency_confidence",
    ]
].mean()

sns.barplot(
    x=mean_metrics.index,
    y=mean_metrics.values,
    ax=axes[0, 0],
    color="#4C78A8",
)
axes[0, 0].set_title("Mean validation metrics")
axes[0, 0].set_ylabel("Score")
axes[0, 0].set_xlabel("")
axes[0, 0].set_ylim(0, 1)
axes[0, 0].tick_params(axis="x", rotation=45)

f1_df = plot_df.melt(
    id_vars="case_id",
    value_vars=["retrieval_f1", "citation_f1"],
    var_name="metric",
    value_name="score",
)

sns.barplot(
    data=f1_df,
    x="case_id",
    y="score",
    hue="metric",
    ax=axes[0, 1],
)
axes[0, 1].set_title("Evidence retrieval vs. answer citation F1")
axes[0, 1].set_ylabel("F1 score")
axes[0, 1].set_xlabel("Validation case")
axes[0, 1].set_ylim(0, 1)

generation_df = plot_df.melt(
    id_vars="case_id",
    value_vars=["rougeL", "self_consistency_confidence"],
    var_name="metric",
    value_name="score",
)

sns.barplot(
    data=generation_df,
    x="case_id",
    y="score",
    hue="metric",
    ax=axes[1, 0],
)
axes[1, 0].set_title("Generated-answer quality and self-consistency")
axes[1, 0].set_ylabel("Score")
axes[1, 0].set_xlabel("Validation case")
axes[1, 0].set_ylim(0, 1)

trace_df = plot_df.melt(
    id_vars="case_id",
    value_vars=["trace_claim_count", "avg_evidence_per_claim"],
    var_name="metric",
    value_name="value",
)

sns.barplot(
    data=trace_df,
    x="case_id",
    y="value",
    hue="metric",
    ax=axes[1, 1],
)
axes[1, 1].set_title("Evidence-trace coverage")
axes[1, 1].set_ylabel("Count")
axes[1, 1].set_xlabel("Validation case")

plt.tight_layout()
plt.show()